### ISSUE TITLE
What's the difference between Bonnie and Clyde?

### ISSUE THREAD

**Issue by ThePat02** [palmerjw/Clyde-plugin-refactor#7]
Hey, just found your plugin. Maybe I overlooked it, but I cannot find any information on what the actually difference between those two Languages is. Is Bonnie just an interpreter for Clyde or its own language? Why should I use one over the other? I think a comparison table could really help users out here!

**Comment by PaganSeaWitch** [comment]
Essentially, I took the Clyde plugin for Godot and refactored it to a great extent. Then I added new features to the language and the plugin itself. Essentially, the main differences at this point are that Bonnie can manage multiple dialogue files at once through BonnieManager whereas Clyde only as an interface to deal with one at a time. Clyde only has line independent logic whereas Bonnie also has line dependent logic. Bonnie returns class objects whereas Clyde returns things as dictionaries.  You can edit Bonnie files in the Godot editor itself unlike Clyde. Bonnie has prerequisite block conditions. Bonnie also has random blocks and has the ability to randomly choose a block rather than having to select it oneself. through BonnieManager you can have global variables using the @ symbol. Also, because I refactored the language logic, it is far easier to add new features of your own to the language. Thats about it but im sure there are some other differences I forgot about. I do need to add documentation on bonnie manager and how it works but ive been sidetracked

**Comment by ThePat02** [comment]
Sounds great! I think the README is a bit confusing on what Bonnie actually is. Is there a VSCode highlighting plugin or would the Clyde one work just fine?

**Comment by PaganSeaWitch** [comment]
The Clyde one should work okayish, It wont get every keyword but for all the regular ones it should work. Idk how to make vscode highlights so I didn't make one myself.

**Comment by ThePat02** [comment]
> The Clyde one should work okayish, It wont get every keyword but for all the regular ones it should work. Idk how to make vscode highlights so I didn't make one myself.

Don't worry. Those changes sound great tho. I'll give Bonnie a try!
